import {
    HomeIcon,
    CalendarIcon,
    DocumentTextIcon,
    UserGroupIcon,
    UserIcon,
    CreditCardIcon,
    ChartBarIcon,
    CogIcon,
    ReceiptRefundIcon,
    BeakerIcon,
    BellAlertIcon,
    ExclamationTriangleIcon,
    UserPlusIcon,
    CalendarDaysIcon,
    DocumentPlusIcon,
    ChevronDownIcon,
    MagnifyingGlassIcon,
    XMarkIcon,
    Bars3Icon,
} from '@heroicons/vue/24/outline'

export default {
    HomeIcon,
    CalendarIcon,
    DocumentTextIcon,
    UserGroupIcon,
    UserIcon,
    CreditCardIcon,
    ChartBarIcon,
    CogIcon,
    ReceiptRefundIcon,
    BeakerIcon,
    BellAlertIcon,
    ExclamationTriangleIcon,
    UserPlusIcon,
    CalendarDaysIcon,
    DocumentPlusIcon,
    ChevronDownIcon,
    MagnifyingGlassIcon,
    XMarkIcon,
    Bars3Icon,
}